version: '2'

services:
  # Local- backend
  # ****************************************
  local:
    container_name: Local
    build:
      context: ./local
    volumes:
      - ./local:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    env_file: 
      - ./local/local.env
    command: npm run start:dev
    networks:
      - nestjs-simultaneous-db-test
    depends_on:
      - mongodb
      - cloud
# Cloud- backend
  # ****************************************
  cloud:
    container_name: Cloud
    build:
      context: ./cloud
    volumes:
      - ./cloud:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
    env_file:
      - ./cloud/cloud.env
    command: npm run start:dev
    networks:
      - nestjs-simultaneous-db-test
    depends_on:
      - mongodb
  #mongodb
  # ****************************************
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ../mongo-data/:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart:  always
    networks:
      - nestjs-simultaneous-db-test
networks:
  nestjs-simultaneous-db-test: 


  
  
    




